//@flow

export const CREATE_COURSE: string = "CREATE_COURSE";
export const LOAD_COURSES_SUCCESS: string = "LOAD_COURSES_SUCCESS";
export const LOAD_AUTHORS_SUCCESS: string = "LOAD_AUTHORS_SUCCESS";
export const CREATE_COURSE_SUCCESS: string = "CREATE_COURSE_SUCCESS";
export const UPDATE_COURSE_SUCCESS: string = "UPDATE_COURSE_SUCCESS";
export const BEGIN_API_CALL: string = "BEGIN_API_CALL";
export const API_CALL_ERROR: string = "API_CALL_ERROR";
export const DELETE_COURSE_OPTIMISTIC: string = "DELETE_COURSE_OPTIMISTIC";
